### ISSUE TITLE
登录页面切换按钮无效

### ISSUE THREAD

**Issue by NEWDSA** [xingyu4j/vue-vben-admin#1]
登录页面无法切换主题模式，无法切换语言
![image](https://user-images.githubusercontent.com/24479035/209280741-3bc905d8-8baa-4e6a-9c75-2021e821505e.png)

**Comment by xingyu4j** [comment]
升级vite4 后有一些问题，最近抽时间弄一弄

**Comment by xingyu4j** [comment]
目前最新版本本地测试是没有问题的了
